/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styled from "styled-components";
import MenuItem from "./MenuItem";

const menuItems = [
  { name: "Item", price: "15.000 đ" },
  { name: "Item", price: "15.000 đ" },
  { name: "Item", price: "15.000 đ" },
  { name: "Item", price: "15.000 đ" },
  { name: "Item", price: "15.000 đ" },
  { name: "Item", price: "15.000 đ" },
  { name: "Item", price: "15.000 đ" },
  { name: "Item", price: "15.000 đ" },
  { name: "Item", price: "15.000 đ" },
  { name: "Item", price: "15.000 đ" },
  { name: "Item", price: "15.000 đ" },
  { name: "Item", price: "15.000 đ" },
];

function MenuItems() {
  return (
    <MenuItemsContainer>
      {menuItems.map((item, index) => (
        <MenuItem key={index} name={item.name} price={item.price} />
      ))}
      <LastMenuItem>
        <ItemImage />
        <ItemName>Item</ItemName>
        <ItemPrice>15.000 đ</ItemPrice>
      </LastMenuItem>
    </MenuItemsContainer>
  );
}

const MenuItemsContainer = styled.section`
  align-self: stretch;
  display: flex;
  gap: 15px;
  font-family: Inter, sans-serif;
  flex-direction: row;
  overflow: auto;
`;

const LastMenuItem = styled.article`
  align-self: start;
  display: flex;
  flex-direction: column;
  align-items: start;
  font-weight: 400;
  padding: 2px 0;
  @media (max-width: 991px) {
    display: none;
  }
`;

const ItemImage = styled.div`
  background-color: #d9d9d9;
  align-self: stretch;
  display: flex;
  height: 125px;
`;

const ItemName = styled.h3`
  color: #000;
  font-size: 20px;
  margin-top: 9px;
`;

const ItemPrice = styled.span`
  color: #d50000;
  font-size: 12px;
  margin-top: 17px;
`;

export default MenuItems;
