/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { render, screen } from "@testing-library/react";
import { expect, test } from "vitest";
import MenuItem from "./MenuItem";

test("renders MenuItem component", () => {
  render(<MenuItem name="Test Item" price="10.000 đ" />);
  expect(screen.getByText("Test Item")).toBeInTheDocument();
  expect(screen.getByText("10.000 đ")).toBeInTheDocument();
});

test("renders add button", () => {
  render(<MenuItem name="Test Item" price="10.000 đ" />);
  const addButton = screen.getByRole("button", { name: /add item/i });
  expect(addButton).toBeInTheDocument();
  expect(addButton).toHaveTextContent("+");
});

test("renders item image placeholder", () => {
  render(<MenuItem name="Test Item" price="10.000 đ" />);
  const imagePlaceholder = screen.getByRole("article").firstChild;
  expect(imagePlaceholder).toHaveStyle("background-color: #d9d9d9");
});
