/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { render, screen } from "@testing-library/react";
import { expect, test } from "vitest";
import MenuItems from "./MenuItems";

test("renders MenuItems component", () => {
  render(<MenuItems />);
  const menuItems = screen.getAllByRole("article");
  expect(menuItems.length).toBe(13);
});

test("renders correct number of menu items", () => {
  render(<MenuItems />);
  const itemNames = screen.getAllByText("Item");
  expect(itemNames.length).toBe(13);
});

test("renders correct price for menu items", () => {
  render(<MenuItems />);
  const prices = screen.getAllByText("15.000 đ");
  expect(prices.length).toBe(13);
});

test("last menu item is hidden on small screens", () => {
  render(<MenuItems />);
  const lastMenuItem = screen.getAllByRole("article")[12];
  expect(getComputedStyle(lastMenuItem).display).toBe("flex");

  // Simulate small screen
  Object.defineProperty(window, "innerWidth", {
    writable: true,
    configurable: true,
    value: 990,
  });
  window.dispatchEvent(new Event("resize"));

  expect(getComputedStyle(lastMenuItem).display).toBe("none");
});
