/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Logo from "./Logo";
import Navigation from "./Navigation";

const Header = () => {
  return (
    <header className="header">
      <Logo />
      <Navigation />
      <style jsx>{`
        .header {
          background-color: #f6b5b5;
          display: flex;
          gap: 40px 100px;
          overflow: hidden;
          padding: 8px 14px;
        }
      `}</style>
    </header>
  );
};

export default Header;
