/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Navigation = () => {
  const navItems = [
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/aae56868fdcb862e605ea9a58584175c78f8bec2f1376557a9d660d8863bf323?placeholderIfAbsent=true&apiKey=c0efc441fe73418b8b7246db17f848b8",
      alt: "Navigation item 1",
    },
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/189297da07ec9868357cb4291401ef50667416493bf889bffb02c9cca138ebca?placeholderIfAbsent=true&apiKey=c0efc441fe73418b8b7246db17f848b8",
      alt: "Navigation item 2",
    },
  ];

  return (
    <nav className="navigation">
      {navItems.map((item, index) => (
        <img
          key={index}
          src={item.src}
          alt={item.alt}
          className={`nav-item ${index === 1 ? "nav-item-last" : ""}`}
          loading="lazy"
        />
      ))}
      <style jsx>{`
        .navigation {
          display: flex;
          gap: 19px;
        }
        .nav-item {
          aspect-ratio: 1.02;
          object-fit: contain;
          object-position: center;
          width: 42px;
        }
        .nav-item-last {
          aspect-ratio: 1;
          width: 40px;
          box-shadow: 0 4px 4px rgba(0, 0, 0, 0.25);
          align-self: start;
          margin: auto 0 auto auto;
        }
      `}</style>
    </nav>
  );
};

export default Navigation;
