version: "3.4"

services:
  payos-demo:
    image: payos-demo-dotnet-core
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - PAYOS_CLIENT_ID={your id}
      - PAYOS_API_KEY={your api key}
      - PAYOS_CHECKSUM_KEY={your checksum key}
