/**
 * This code was generated by Builder.io.
 */
import React from "react";

const ContactInfo = ({ items }) => {
  return (
    <div className="contact-info">
      {items.map((item, index) => (
        <div key={index} className="contact-item">
          <img src={item.icon} alt="" className="contact-icon" />
          <span className="contact-text">{item.text}</span>
        </div>
      ))}
      <style jsx>{`
        .contact-info {
          display: flex;
          flex-direction: column;
          gap: 20px;
        }
        .contact-item {
          display: flex;
          gap: 16px;
          font-weight: 500;
          align-items: center;
        }
        .contact-icon {
          aspect-ratio: 1;
          object-fit: contain;
          width: 24px;
        }
        .contact-text {
          flex-basis: auto;
        }
      `}</style>
    </div>
  );
};

export default ContactInfo;
