/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Copyright = () => {
  return (
    <div className="copyright">
      Copyrighted © 2024 Assits Ordering System.
      <style jsx>{`
        .copyright {
          background-color: #553434;
          margin-top: 33px;
          overflow: hidden;
          font-size: 14px;
          color: #fff;
          padding: 12px 37px;
        }
      `}</style>
    </div>
  );
};

export default Copyright;
