

/**
 * This code was generated by Builder.io.
 */
import React from "react";

const FooterLinks = ({ title, items }) => {
  return (
    <nav className="footer-links">
      <h2 className="footer-links-title">{title}</h2>
      <ul className="footer-links-list">
        {items.map((item, index) => (
          <li key={index} className="footer-link-item">
            <a href="#" className="footer-link">
              {item}
            </a>
          </li>
        ))}
      </ul>
      <style jsx>{`
        .footer-links {
          margin-top: 20px;
        }
        .footer-links-title {
          font-weight: 700;
          margin: 0 0 16px 25px;
          font-size: 16px;
        }
        .footer-links-list {
          list-style-type: none;
          padding: 0;
          margin: 0;
        }
        .footer-link-item {
          margin: 9px 0 0 25px;
        }
        .footer-link {
          font-size: 14px;
          color: #000;
          text-decoration: none;
                    text-decoration: underline;
        }
      `}</style>
    </nav>
  );
};

export default FooterLinks;
