/**
 * This code was generated by Builder.io.
 */
import React from "react";
import ContactInfo from "./ContactInfo";
import FooterLinks from "./FooterLinks";
import Copyright from "./Copyright";

const Footer = () => {
  const contactItems = [
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/c3aac47b727a6612500a96595a3b4d9dea0e4aefb355edcbc066da9019801d47?placeholderIfAbsent=true&apiKey=c0efc441fe73418b8b7246db17f848b8",
      text: "Hotline: 0967375045",
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/958d2628ee54563e2bd440632e1f0ac71b655aba4be5db360de18f694a6593ec?placeholderIfAbsent=true&apiKey=c0efc441fe73418b8b7246db17f848b8",
      text: "Mail: dungthhe170357@fpt.edu.vn",
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/259d79add37fc95f3d1523bdcd472dc9158a67373e6e6ef3b90165fe08b90b77?placeholderIfAbsent=true&apiKey=c0efc441fe73418b8b7246db17f848b8",
      text: "Contact",
    },
  ];

  const linkItems = ["About us", "Contact"];

  return (
    <footer className="footer">
      <div className="footer-content">
        <ContactInfo items={contactItems} />
        <address className="address">
          2G7G+8F3, Thạch Hoà, Thạch Thất, Hà Nội, Vietnam
        </address>
        <img
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/01b1ac975c883874a9251382d0fac643e51155a65744cab318a1afa1ef964ae8?placeholderIfAbsent=true&apiKey=c0efc441fe73418b8b7246db17f848b8"
          alt="Company logo"
          className="company-logo"
        />
        <FooterLinks title="Information" items={linkItems} />
      </div>
      <Copyright />
      <style jsx>{`
        .footer {
          background-color: #f6b5b5;
          display: flex;
          padding-top: 26px;
          flex-direction: column;
          overflow: hidden;
          font-family: Inter, sans-serif;
        }
        .footer-content {
          display: flex;
          width: 100%;
          flex-direction: column;
          align-items: flex-start;
          font-size: 16px;
          color: #000;
          padding: 0 43px 0 16px;
        }
        .address {
          color: rgba(0, 0, 0, 0.6);
          font-size: 14px;
          margin-top: 20px;
          font-style: normal;
        }
        .company-logo {
          aspect-ratio: 2.14;
          object-fit: contain;
          width: 201px;
          align-self: center;
          margin-top: 20px;
          max-width: 100%;
        }
      `}</style>
    </footer>
  );
};

export default Footer;
