/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styled from "styled-components";
import TopBar from "./TopBar";
import LoginForm from "./LoginForm";

function LoginPage() {
  return (
    <StyledLoginPage>
      <TopBar />
      <main className="login-content">
        <BackgroundImage
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/b6d8f28586572e49309eab4c6ca85ba6b7d149462a3c9b76f73f9ca4b748dd43?placeholderIfAbsent=true&apiKey=bdbb4ff9c991480cb550a43f2a4fe7d6"
          alt=""
        />
        <LoginForm />
      </main>
    </StyledLoginPage>
  );
}

const StyledLoginPage = styled.div`
  background-color: #fff;
  display: flex;
  flex-direction: column;
  overflow: hidden;

  .login-content {
    display: flex;
    flex-direction: column;
    position: relative;
    aspect-ratio: 0.497;
    width: 100%;
    font-family: Inter, sans-serif;
    justify-content: center;
    padding: 275px 15px;
  }

  @media (max-width: 640px) {
    align-self: stretch;
    max-width: 500px;
  }
`;

const BackgroundImage = styled.img`
  position: absolute;
  inset: 0;
  height: 100%;
  width: 100%;
  object-fit: cover;
  object-position: center;
`;

export default LoginPage;
