/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styled from "styled-components";

function LoginForm() {
  return (
    <StyledLoginForm>
      <h2 className="form-title">MEMBER LOGIN</h2>
      <form className="login-form">
        <div className="input-wrapper">
          <img
            className="phone-icon"
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/8c204c2ca958852becc5bb2b266bd29de548c6af59f439959726ce4f579c4009?placeholderIfAbsent=true&apiKey=bdbb4ff9c991480cb550a43f2a4fe7d6"
            alt=""
          />
          <label htmlFor="phoneInput" className="visually-hidden">
            Enter phone number
          </label>
          <input
            id="phoneInput"
            type="tel"
            placeholder="Enter phone number..."
            aria-label="Enter phone number"
          />
        </div>
        <button type="submit" className="login-button">
          Login
        </button>
      </form>
    </StyledLoginForm>
  );
}

const StyledLoginForm = styled.section`
  position: relative;
  border-radius: 31px;
  background-color: #fff;
  box-shadow: 0 0 10px rgba(0, 0, 0, 0.25);
  display: flex;
  margin-bottom: -63px;
  width: 100%;
  flex-direction: column;
  align-items: center;
  padding: 21px 26px;

  .form-title {
    color: var(--Azzan-Color, #bd3326);
    text-align: center;
    font-size: 20px;
    font-weight: 700;
    margin: 0 0 31px;
  }

  .login-form {
    width: 100%;
  }

  .input-wrapper {
    border-radius: 6px;
    border: var(--sds-size-stroke-focus-ring) solid var(--Azzan-Color, #bd3326);
    display: flex;
    gap: 10px;
    font-size: 16px;
    color: #000;
    font-weight: 400;
    padding: 10px;
    margin-bottom: 22px;
  }

  .phone-icon {
    aspect-ratio: 1;
    object-fit: contain;
    object-position: center;
    width: 20px;
    fill: var(--Azzan-Color, #bd3326);
  }

  input {
    flex-grow: 1;
    width: 230px;
    border: none;
    outline: none;
    font-size: 16px;
  }

  .login-button {
    width: 100%;
    border-radius: var(--sds-size-radius-200);
    border: 0.5px solid var(--sds-color-border-brand-default);
    background: var(--Azzan-Color, #bd3326);
    color: var(--sds-color-text-brand-on-brand);
    padding: var(--sds-size-space-300);
    font: var(--sds-typography-body-font-weight-regular)
      var(--sds-typography-body-size-medium) / 1
      var(--sds-typography-body-font-family);
    cursor: pointer;
  }

  .visually-hidden {
    position: absolute;
    width: 1px;
    height: 1px;
    padding: 0;
    margin: -1px;
    overflow: hidden;
    clip: rect(0, 0, 0, 0);
    white-space: nowrap;
    border: 0;
  }
`;

export default LoginForm;
