/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { render, screen } from "@testing-library/react";
import { describe, it, expect } from "vitest";
import LoginPage from "./LoginPage";

describe("LoginPage", () => {
  it("renders without crashing", () => {
    render(<LoginPage />);
    expect(screen.getByText("MEMBER LOGIN")).toBeInTheDocument();
  });

  it("contains a login form", () => {
    render(<LoginPage />);
    expect(screen.getByRole("form")).toBeInTheDocument();
  });

  it("has an accessible phone number input", () => {
    render(<LoginPage />);
    const input = screen.getByLabelText("Enter phone number");
    expect(input).toBeInTheDocument();
    expect(input).toHaveAttribute("type", "tel");
  });

  it("has a submit button", () => {
    render(<LoginPage />);
    expect(screen.getByRole("button", { name: "Login" })).toBeInTheDocument();
  });
});
