/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styled from "styled-components";

function TopBar() {
  return (
    <StyledTopBar>
      <img
        className="logo"
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/36f960c7f7d0b980f3db114ef7487d4841d6425178f3cb433e7074ecf69bf393?placeholderIfAbsent=true&apiKey=bdbb4ff9c991480cb550a43f2a4fe7d6"
        alt="Company Logo"
      />
    </StyledTopBar>
  );
}

const StyledTopBar = styled.header`
  background-color: rgba(229, 44, 44, 0.35);
  display: flex;
  width: 100%;
  justify-content: center;
  padding: 17px 24px;

  .logo {
    aspect-ratio: 7.25;
    object-fit: contain;
    object-position: center;
    width: 304px;

    @media (max-width: 991px) {
      width: 100%;
    }
  }
`;

export default TopBar;
