/**
 * This code was generated by Builder.io.
 */
const PriceItem = ({ label, value, isTotal }) => {
    return (
        <div className={`price-item ${isTotal ? "total" : ""}`}>
            <span className="label1">{label}</span>
            <span className="value">{value}</span>
            <style jsx>{`
        .price-item {
          color: var(--primary-color);
          font: 400 16px Inter, sans-serif;
          margin: 8px 0;
          width: 100%;
        }
        .total {
          font-weight: 600;
        }
        .label1 {
          float: left;
        }
        .value {
          float: right;
        }
      `}</style>
        </div>
    );
};

export default PriceItem;