/**
 * This code was generated by Builder.io.
 */
import React from "react";

const PriceItem = ({ label, value, isTotal }) => {
  return (
    <p className={`price-item ${isTotal ? "total" : ""}`}>
      {label}
      <style jsx>{`
        .price-item {
          color: var(--Azzan-Color, #bd3326);
          font: 400 16px Inter, sans-serif;
          margin: 8px 0;
        }
        .total {
          font-weight: 600;
        }
      `}</style>
    </p>
  );
};    

export default PriceItem;
