/**
 * This code was generated by Builder.io.
 */
import React from "react";

const TotalPrice = () => {
  return (
    <div className="total-price-container">
      <div className="voucher-input">
        <img
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/170034c8ccaf3722be922eaa999b1f02f19585d5b327ad61ff50748511ec2953?placeholderIfAbsent=true&apiKey=c0efc441fe73418b8b7246db17f848b8"
          alt=""
          className="voucher-icon"
        />
      </div>
      <div className="price-values">
        <p className="discount-price">0 đ</p>
        <p className="final-price">105.000 đ</p>
        <img
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/3daa88c596f12764a69508098612d6d3ba5839873c031a93b1ac416fd8d5c0b9?placeholderIfAbsent=true&apiKey=c0efc441fe73418b8b7246db17f848b8"
          alt=""
          className="payment-icon"
        />
      </div>
      <style jsx>{`
        .total-price-container {
          display: flex;
          flex-direction: column;
        }
        .voucher-input {
          border-radius: 5px;
          background-color: #fff;
          display: flex;
          justify-content: center;
          padding: 2px 32px;
          border: 1px solid #bd3326;
        }
        .voucher-icon {
          aspect-ratio: 1.1;
          object-fit: contain;
          width: 22px;
        }
        .price-values {
          display: flex;
          margin-top: 11px;
          padding-left: 32px;
          flex-direction: column;
          align-items: flex-end;
          color: var(--Azzan-Color, #bd3326);
          text-align: right;
          font: 600 16px Inter, sans-serif;
        }
        .discount-price,
        .final-price {
          text-decoration: underline;
        }
        .final-price {
          margin-top: 16px;
        }
        .payment-icon {
          aspect-ratio: 1;
          object-fit: contain;
          width: 30px;
          margin-top: 8px;
        }
      `}</style>
    </div>
  );
};

export default TotalPrice;
