/**
 * This code was generated by Builder.io.
 */
import React from "react";
import CartItem from "./CartItem";
import MenuSeparator from "./MenuSeparator";

const ItemInCart = ({ name, options, price, quantity }) => {
  const cartItems = [
      {
          name: name,
          options: options,
          price: price,
          quantity: quantity,
    },
  ];

  return (
    <section className="item-in-cart">
      {cartItems.map((item, index) => (
        <React.Fragment key={index}>
          <CartItem {...item} />
          <MenuSeparator />
        </React.Fragment>
      ))}
      <style jsx>{`
        .item-in-cart {
          border-radius: 0;
          display: flex;
          max-width: 284px;
          flex-direction: column;
        }
      `}</style>
    </section>
  );
};

export default ItemInCart;
