/**
 * This code was generated by Builder.io.
 */
import React from "react";

const MenuSeparator = () => {
  return (
    <div className="menu-separator">
      <div className="separator-line" />
      <style jsx>{`
        .menu-separator {
          border-radius: 8px;
          align-self: start;
          display: flex;
          min-height: 16px;
          flex-direction: column;
          justify-content: center;
          padding: 8px 16px;
        }
        .separator-line {
          background-color: rgba(0, 0, 0, 0.25);
          display: flex;
          min-height: 1px;
          width: 100%;
        }
      `}</style>
    </div>
  );
};

export default MenuSeparator;
